#!/bin/sh
WORKING_BRANCH=`git rev-parse --abbrev-ref HEAD`
DEFAULT_BRANCH=`basename $(git symbolic-ref refs/remotes/origin/HEAD)`
if [ "$DEFAULT_BRANCH" != "$WORKING_BRANCH" ]; then
  git switch $DEFAULT_BRANCH
fi
git branch --format='%(refname:short) %(worktreepath)' --merged | while read BRANCH_NAME WORKTREE_PATH
  do
    if [ -z "$WORKTREE_PATH" ]; then
      git branch -d $BRANCH_NAME
    elif [ "$BRANCH_NAME" != "$DEFAULT_BRANCH" ]; then
      echo "worktree $BRANCH_NAME"
    fi
  done
git fetch --prune
for BRANCH_REF in $(git branch -v | grep '\[gone\]' | grep '^+' | awk '{print $3}')
  do
    git worktree remove `git worktree list | grep $BRANCH_REF | awk '{print $1}'`
  done
for BRANCH_NAME in $(git branch -v | grep '\[gone\]' | awk '{print $1}')
  do
    git branch -D $BRANCH_NAME
  done
if [ "$DEFAULT_BRANCH" != "$WORKING_BRANCH" ]; then
  git switch $WORKING_BRANCH
fi
